version: '3.7'
services:
  web:
    build: .
    ports:
      - 80:80
    depends_on:
      - db
    volumes:
      - ./:/var/www/html/
      - ./.etc/conf/apache/vhosts:/etc/apache2/sites-enabled
      - ./.etc/conf/php/90-overrides.ini:/usr/local/etc/php/conf.d/90-overrides.ini
      - ./log:/var/log/apache2
    restart: unless-stopped
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: apsl
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1234
    volumes:
      - ./.etc/mysql:/var/lib/mysql
    ports:
      - 3306:3306
